In [1]:
import pandas as pd

In [5]:
df_bus = pd.read_csv("/Users/riccardofiorista/Documents/urops/dtemkin1/framingham-bus/data/busses.csv")
df_out = pd.read_csv("/Users/riccardofiorista/Downloads/buses.csv")
df_orig = pd.read_excel("/Users/riccardofiorista/Documents/urops/dtemkin1/framingham-bus/data/from_framingham/Framingham Schools - Bus Fleet List (1).xlsx")

In [3]:
df_out

                   id depot_name  capacity   range  has_wheelchair_access
0   4UZABRFA6NCNM1199      DEPOT        71  241402                  False
1   4UZABRFA9NCNM1200      DEPOT        71  241402                  False
2   4UZABRFA0NCNM1201      DEPOT        71  241402                  False
3   4UZABRFA2NCNM1202      DEPOT        71  241402                  False
4   4UZABRFA4NCNM1203      DEPOT        71  241402                  False
..                ...        ...       ...     ...                    ...
67  4UZABPFA4NCNM1268      DEPOT        48  241402                  False
68  4UZABPFA6NCNM1269      DEPOT        48  241402                  False
69  4UZABPFA2NCNM1270      DEPOT        48  241402                  False
70  4UZABPFA4NCNM1271      DEPOT        48  241402                  False
71  4UZABRFA8NCNN0874      DEPOT         4  241402                   True

[72 rows x 5 columns]

In [4]:
df_bus

,Category,Class,Vehicle Type,Vehicle use type,Model year,Make,Model,Contract#
0,71 passenger,SCHOOLBUSTYPEC,"SCHOOL BUS TYPE C <33,000 GVW",STUDENT,2022,Freightliner,Saf-T-Liner,Framingham Public Schools
1,71 passenger,SCHOOLBUSTYPEC,"SCHOOL BUS TYPE C <33,000 GVW",STUDENT,2022,Freightliner,Saf-T-Liner,Framingham Public Schools
2,71 passenger,SCHOOLBUSTYPEC,"SCHOOL BUS TYPE C <33,000 GVW",STUDENT,2022,Freightliner,Saf-T-Liner,Framingham Public Schools
3,71 passenger,SCHOOLBUSTYPEC,"SCHOOL BUS TYPE C <33,000 GVW",STUDENT,2022,Freightliner,Saf-T-Liner,Framingham Public Schools
4,71 passenger,SCHOOLBUSTYPEC,"SCHOOL BUS TYPE C <33,000 GVW",STUDENT,2022,Freightliner,Saf-T-Liner,Framingham Public Schools
...,...,...,...,...,...,...,...,...
67,48 passenger bus,SCHOOLBUSTYPEB,"SCHOOL BUS TYPE B <26,000 GVW",STUDENT,2022,Freightliner,Saf-T-Liner,Framingham Public Schools
68,48 passenger bus,SCHOOLBUSTYPEB,"SCHOOL BUS TYPE B <26,000 GVW",STUDENT,2022,Freightliner,Saf-T-Liner,Framingham Public Schools
69,48 passenger bus,SCHOOLBUSTYPEB,"SCHOOL BUS TYPE B <26,000 GVW",STUDENT,2022,Freightliner,Saf-T-Liner,Framingham Public Schools
70,48 passenger bus,SCHOOLBUSTYPEB,"SCHOOL BUS TYPE B <26,000 GVW",STUDENT,2022,Freightliner,Saf-T-Liner,Framingham Public Schools
71,4 wheelchair bus,SCHLBUSTYPEBWC,"SCHOOL BUS TYPE B WC <33,000 GVW",STUDENT,2022,Freightliner,Saf-T-Liner,Framingham Public Schools

In [7]:
df_orig.columns = [col.replace(' ', '_').lower() for col in df_orig.columns]

In [11]:
type_only = df_orig[['vehicle_id', 'vehicle_type']]
type_only['vehicle_type'].unique()

<StringArray>
[   'SCHOOL BUS TYPE C <33,000 GVW', 'SCHOOL BUS TYPE B WC <33,000 GVW',
    'SCHOOL BUS TYPE B <26,000 GVW']
Length: 3, dtype: str

In [14]:
type_only['vehicle_type'] = type_only['vehicle_type'].str.replace('SCHOOL BUS TYPE ', '', regex=False).str.replace(' <33,000 GVW', '', regex=False).str.replace(' <26,000 GVW', '', regex=False).str.replace(' ', '', regex=False)

In [18]:
df_out = df_out.merge(type_only.rename(columns={'vehicle_id': 'id'}), on='id', how='left')

In [20]:
df_out = df_out.rename(columns={'vehicle_type': 'type'})

In [22]:
df_out.to_csv('./data/buses.csv', index=False)

In [ ]:
df_out.loc[df_out['type'] == 'BWC', 'range'] = 360
df_out.loc[df_out['type'] == 'C', 'range'] = 300
df_out.loc[df_out['type'] == 'B', 'range'] = 300

In [29]:
df_out.to_csv('./data/buses.csv', index=False)